Removed more traces of the unix sigalrm port

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -443,12 +443,6 @@ AC_SUBST(ALLEGRO_MAYBE_LIB_X_EXE_SOURCES)
 AC_SUBST(ALLEGRO_MAYBE_LIB_X_EXES)
 AC_SUBST(ALLEGRO_XWINDOWS_LIBDIR)
 
-dnl Enable pthreads
-AC_ARG_ENABLE(pthreads,
-[  --enable-pthreads[=x]   enable use of pthreads [default=yes]],
-test "X$enableval" != "Xno" && allegro_enable_pthreads=yes,
-allegro_enable_pthreads=yes)
-
 dnl Enable Linux console support
 AC_ARG_ENABLE(linux,
 [  --enable-linux[=x]      enable Linux console support [default=yes]],
@@ -554,32 +548,21 @@ esac
 
 AC_SUBST(ALLEGRO_MAYBE_LINUX_FILES)
 
-_do_pthread="no"
 dnl Test for pthreads.
-if test "X$allegro_enable_pthreads" = "Xyes"; then
-  ALLEGRO_ACTEST_PTHREADS
-  if test "X$allegro_cv_support_pthreads" = "Xyes"; then
-    AC_DEFINE(HAVE_LIBPTHREAD,1, [Define if you have the pthread library.])
-    _do_pthread="yes"
-  fi
-fi
-
-if test "$_do_pthread" = yes; then
-  _code_features="multithreaded, $_code_features"
+ALLEGRO_ACTEST_PTHREADS
+if test "X$allegro_cv_support_pthreads" = "Xyes"; then
+  AC_DEFINE(HAVE_LIBPTHREAD,1, [Define if you have the pthread library.])
 else
-  _code_features="signals instead of threads, $_code_features"
+  dnl XXX: sorry, I don't know how to make this fail properly --pw
+  echo "ERROR: You don't have pthreads, which is required by Allegro."
+  exit 1
 fi
 
 dnl Test for JACK driver
 ALLEGRO_ACTEST_JACK
 if test "X$allegro_cv_support_jackdigi" = "Xyes"; then
-  if test "X$_do_pthread" = "Xyes"; then
-    AC_DEFINE(ALLEGRO_WITH_JACKDIGI,1,[Define if JACK DIGI driver is supported.])
-    _enabled_modules="jackdigi $_enabled_modules"
-  else
-	echo Warning: Jack will be disabled, since pthreads support is missing/disabled.
-	_disabled_modules="jackdigi $_disabled_modules"
-  fi
+  AC_DEFINE(ALLEGRO_WITH_JACKDIGI,1,[Define if JACK DIGI driver is supported.])
+  _enabled_modules="jackdigi $_enabled_modules"
 else
   _disabled_modules="jackdigi $_disabled_modules"
 fi
