Make cross references work for Info, LaTeX output in the documentation system.
Make docs/scripts/make_* consistently use --output to specify output files.

Add CMake target to build PDF of the manual using pdflatex.

diff --git a/docs/scripts/make_html_refs b/docs/scripts/make_html_refs
--- a/docs/scripts/make_html_refs
+++ b/docs/scripts/make_html_refs
@@ -2,11 +2,7 @@
 #
 # SYNOPSIS
 #
-# make_html_refs [OPTIONS] DOC-FILE...
-#
-# OPTIONS
-#
-# --html-refs FILE
+# make_html_refs --output OUTPUT-FILE DOC-FILE...
 #
 # DESCRIPTION
 #
@@ -15,14 +11,8 @@
 #
 #   [bar]: foo.html#bar
 #
-# ENVIRONMENT VARIABLES
-#
-# - HTML_REFS
-#
 
 set -e
-
-HTML_REFS=${HTML_REFS:-html_refs}
 
 # Speed up grep and sed.
 export LC_ALL=C
@@ -36,14 +26,18 @@ make_html_refs() {
 }
 
 case $1 in
-    --html-refs)
-        HTML_REFS=$2
+    -o|--output)
+        OUTPUT=$2
         shift 2
+        ;;
+    *)
+        echo "make_html_refs: Missing output file." 1>&2
+        exit 1
         ;;
 esac
 
 for file; do
     make_html_refs "$file"
-done > "$HTML_REFS"
+done > "$OUTPUT"
 
 # vim: set et:
diff --git a/docs/scripts/make_protos b/docs/scripts/make_protos
--- a/docs/scripts/make_protos
+++ b/docs/scripts/make_protos
@@ -2,33 +2,26 @@
 #
 # SYNOPSIS
 #
-# make_protos [OPTIONS...] SOURCE-FILE...
-#
-# OPTIONS
-#
-# --protos FILE
+# make_protos --output OUTPUT-FILE SOURCE-FILE...
 #
 # DESCRIPTION
 #
 # Extract all the function prototypes and type/enum declarations which have
 # Natural Docs tags Function: Type: Enum:
-# Output goes to $PROTOS.
-#
-# ENVIRONMENT VARIABLES
-#
-# - PROTOS
 #
 
 set -e
 
 export LC_CTYPE=C
 
-PROTOS=${PROTOS:-protos}
-
 case $1 in
-    --protos)
+    --output)
         PROTOS=$2
         shift 2
+        ;;
+    *)
+        echo "make_protos: Missing --output options." 1>&2
+        exit 1
         ;;
 esac
 
